### ISSUE TITLE
invalid API URL

### ISSUE THREAD

**Issue by movAX13h** [Xlinka/TikTok-Downloader#1]
The tiktok api url does not seem to work anymore.

**Comment by Xlinka** [comment]
Hello can you test the API endpoint I just pushed in https://github.com/Xlinka/TikTok-Downloader/commit/dff32f9eb01cd16b0db0a504b9a6a287ffbc5d0d

**Comment by x5qubits** [comment]
Still not working

**Comment by TanLocc** [comment]
I live in Vietnam and when I run your code, I get empty content
![image](https://github.com/Xlinka/TikTok-Downloader/assets/48042137/1560e4b2-6524-4978-8f03-9c97f9f70fdb)

**Comment by Xlinka** [comment]
@TanLocc @movAX13h @x5qubits 
https://github.com/Xlinka/TikTok-Downloader/commit/f74eb5478944a26cd96977d02a2c5234e4d83ca9

fixed the URL and downloading in latest and added a basic logger incase of errors.
